# MATH 210 Introduction to Mathematical Computing

## November 20, 2020

* Linear algebra with SciPy
* Creating matrices
* Matrix multiplication
* Inverses, determinant and transpose
* Solving systems of linear equations

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Linear algebra with SciPy

[`scipy.linalg`](https://docs.scipy.org/doc/scipy/reference/linalg.html) is the linear algebra subpackage in SciPy. There is also `numpy.linalg`. These subpackages have a lot of the same things. We prefer `scipy.linalg`.

In [2]:
import scipy.linalg as la

### Matrix Multiplication

Matrix multiplication is given by the `@` operator:

In [3]:
M1 = np.array([[1,2],[3,4]])
print(M1)

[[1 2]
 [3 4]]


In [4]:
M2 = np.array([[1,-1],[1,1]])
print(M2)

[[ 1 -1]
 [ 1  1]]


In [5]:
M1 @ M2

array([[3, 1],
       [7, 1]])

Recall `*` defines entry-by-entry multiplication (or array multiplication):

In [6]:
M1 * M2

array([[ 1, -2],
       [ 3,  4]])

There is no operator for matrix powers. We can use `@` several times to compute powers. For example, $M_1^3$ then we can do:

In [7]:
M1 @ M1 @ M1

array([[ 37,  54],
       [ 81, 118]])

Note that `M1^3` is **not** to the power 3 and neither is `M1**3`.

In [8]:
M1**3

array([[ 1,  8],
       [27, 64]])

I **think** the reason why there is not an easily accessible matrix power operator is because we shouldn't be computing high powers of a matrix by matrix multiplication. We should use diagonalization.

... but if we really want a matrix power function then there is `scipy.linalg.fractional_matrix_power`.

In [9]:
from scipy.linalg import fractional_matrix_power as mpow

In [10]:
mpow(M1,3)

array([[ 37,  54],
       [ 81, 118]])

## Special matrices

In [11]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Inverses and determinants

Compute the inverse with `scipy.linalg.inv` and compute the determinant with `scipy.linalg.det`.

In [13]:
M1_inv = la.inv(M1)
M1_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
M1 @ M1_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [15]:
M1_inv @ M1

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [16]:
la.det(M1)

-2.0

The transpose is given by `M1.T`.

In [17]:
M1.T

array([[1, 3],
       [2, 4]])

## Solve linear systems

A linear system of equations is a matrix equation

$$
A \mathbf{x} = \mathbf{b}
$$

It's not usually a good idea to use the inverse to compute
$$
\mathbf{x} = A^{-1} \mathbf{b}
$$
because computing the inverse is computationally intensive. Instead use `scipy.linalg.solve`.

In [18]:
N = 3
A = np.random.randint(-5,5,[N,N])
b = np.random.randint(-5,5,[N,1])
print('A =')
print(A)
print('b =')
print(b)

A =
[[ 1 -3 -4]
 [ 3 -2 -3]
 [ 2 -5  4]]
b =
[[-1]
 [ 4]
 [ 1]]


In [19]:
Ainv = la.inv(A)
x = Ainv @ b
print(x)

[[2.02666667]
 [0.76      ]
 [0.18666667]]


In [20]:
x = la.solve(A,b)
print(x)

[[2.02666667]
 [0.76      ]
 [0.18666667]]


In [21]:
A@x

array([[-1.],
       [ 4.],
       [ 1.]])

But now let's time both methods for large `N`.

In [22]:
N = 100
A = np.random.randint(-5,5,[N,N])
b = np.random.randint(-5,5,[N,1])

In [23]:
%%timeit
Ainv = la.inv(A)
x = Ainv @ b

3.01 s ± 221 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%%timeit
x = la.solve(A,b)

2.14 s ± 151 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


`scipy.linalg.solve` is faster than using the inverse!